// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistic.proto

package org.corps.bi.datacenter.server.statistics.proto;

public final class StatisticsProto {
  private StatisticsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_statistics_StorageStatisticKeyProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_statistics_StorageStatisticKeyProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017statistic.proto\022\nstatistics\"T\n\030Storage" +
      "StatisticKeyProto\022\016\n\006metric\030\001 \001(\t\022\014\n\004snI" +
      "d\030\002 \001(\t\022\016\n\006gameId\030\003 \001(\t\022\n\n\002ds\030\004 \001(\tBD\n/o" +
      "rg.corps.bi.datacenter.server.statistics" +
      ".protoB\017StatisticsProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_statistics_StorageStatisticKeyProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_statistics_StorageStatisticKeyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_statistics_StorageStatisticKeyProto_descriptor,
        new java.lang.String[] { "Metric", "SnId", "GameId", "Ds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
