// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistic.proto

package org.corps.bi.datacenter.server.statistics.proto;

/**
 * Protobuf type {@code statistics.StorageStatisticKeyProto}
 */
public  final class StorageStatisticKeyProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:statistics.StorageStatisticKeyProto)
    StorageStatisticKeyProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StorageStatisticKeyProto.newBuilder() to construct.
  private StorageStatisticKeyProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StorageStatisticKeyProto() {
    metric_ = "";
    snId_ = "";
    gameId_ = "";
    ds_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StorageStatisticKeyProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            metric_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            snId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            gameId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ds_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.datacenter.server.statistics.proto.StatisticsProto.internal_static_statistics_StorageStatisticKeyProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.datacenter.server.statistics.proto.StatisticsProto.internal_static_statistics_StorageStatisticKeyProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.class, org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.Builder.class);
  }

  public static final int METRIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object metric_;
  /**
   * <code>string metric = 1;</code>
   */
  public java.lang.String getMetric() {
    java.lang.Object ref = metric_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metric_ = s;
      return s;
    }
  }
  /**
   * <code>string metric = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMetricBytes() {
    java.lang.Object ref = metric_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metric_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNID_FIELD_NUMBER = 2;
  private volatile java.lang.Object snId_;
  /**
   * <code>string snId = 2;</code>
   */
  public java.lang.String getSnId() {
    java.lang.Object ref = snId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      snId_ = s;
      return s;
    }
  }
  /**
   * <code>string snId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSnIdBytes() {
    java.lang.Object ref = snId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      snId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAMEID_FIELD_NUMBER = 3;
  private volatile java.lang.Object gameId_;
  /**
   * <code>string gameId = 3;</code>
   */
  public java.lang.String getGameId() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameId_ = s;
      return s;
    }
  }
  /**
   * <code>string gameId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGameIdBytes() {
    java.lang.Object ref = gameId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DS_FIELD_NUMBER = 4;
  private volatile java.lang.Object ds_;
  /**
   * <code>string ds = 4;</code>
   */
  public java.lang.String getDs() {
    java.lang.Object ref = ds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ds_ = s;
      return s;
    }
  }
  /**
   * <code>string ds = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDsBytes() {
    java.lang.Object ref = ds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMetricBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, metric_);
    }
    if (!getSnIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, snId_);
    }
    if (!getGameIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gameId_);
    }
    if (!getDsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ds_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMetricBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, metric_);
    }
    if (!getSnIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, snId_);
    }
    if (!getGameIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gameId_);
    }
    if (!getDsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ds_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto)) {
      return super.equals(obj);
    }
    org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto other = (org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto) obj;

    boolean result = true;
    result = result && getMetric()
        .equals(other.getMetric());
    result = result && getSnId()
        .equals(other.getSnId());
    result = result && getGameId()
        .equals(other.getGameId());
    result = result && getDs()
        .equals(other.getDs());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRIC_FIELD_NUMBER;
    hash = (53 * hash) + getMetric().hashCode();
    hash = (37 * hash) + SNID_FIELD_NUMBER;
    hash = (53 * hash) + getSnId().hashCode();
    hash = (37 * hash) + GAMEID_FIELD_NUMBER;
    hash = (53 * hash) + getGameId().hashCode();
    hash = (37 * hash) + DS_FIELD_NUMBER;
    hash = (53 * hash) + getDs().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code statistics.StorageStatisticKeyProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:statistics.StorageStatisticKeyProto)
      org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.datacenter.server.statistics.proto.StatisticsProto.internal_static_statistics_StorageStatisticKeyProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.datacenter.server.statistics.proto.StatisticsProto.internal_static_statistics_StorageStatisticKeyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.class, org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.Builder.class);
    }

    // Construct using org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      metric_ = "";

      snId_ = "";

      gameId_ = "";

      ds_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.datacenter.server.statistics.proto.StatisticsProto.internal_static_statistics_StorageStatisticKeyProto_descriptor;
    }

    public org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto getDefaultInstanceForType() {
      return org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.getDefaultInstance();
    }

    public org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto build() {
      org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto buildPartial() {
      org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto result = new org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto(this);
      result.metric_ = metric_;
      result.snId_ = snId_;
      result.gameId_ = gameId_;
      result.ds_ = ds_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto) {
        return mergeFrom((org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto other) {
      if (other == org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto.getDefaultInstance()) return this;
      if (!other.getMetric().isEmpty()) {
        metric_ = other.metric_;
        onChanged();
      }
      if (!other.getSnId().isEmpty()) {
        snId_ = other.snId_;
        onChanged();
      }
      if (!other.getGameId().isEmpty()) {
        gameId_ = other.gameId_;
        onChanged();
      }
      if (!other.getDs().isEmpty()) {
        ds_ = other.ds_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object metric_ = "";
    /**
     * <code>string metric = 1;</code>
     */
    public java.lang.String getMetric() {
      java.lang.Object ref = metric_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metric_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metric = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMetricBytes() {
      java.lang.Object ref = metric_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metric = 1;</code>
     */
    public Builder setMetric(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metric_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string metric = 1;</code>
     */
    public Builder clearMetric() {
      
      metric_ = getDefaultInstance().getMetric();
      onChanged();
      return this;
    }
    /**
     * <code>string metric = 1;</code>
     */
    public Builder setMetricBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metric_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object snId_ = "";
    /**
     * <code>string snId = 2;</code>
     */
    public java.lang.String getSnId() {
      java.lang.Object ref = snId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        snId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string snId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSnIdBytes() {
      java.lang.Object ref = snId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        snId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string snId = 2;</code>
     */
    public Builder setSnId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      snId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string snId = 2;</code>
     */
    public Builder clearSnId() {
      
      snId_ = getDefaultInstance().getSnId();
      onChanged();
      return this;
    }
    /**
     * <code>string snId = 2;</code>
     */
    public Builder setSnIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      snId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gameId_ = "";
    /**
     * <code>string gameId = 3;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gameId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gameId = 3;</code>
     */
    public Builder setGameId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gameId = 3;</code>
     */
    public Builder clearGameId() {
      
      gameId_ = getDefaultInstance().getGameId();
      onChanged();
      return this;
    }
    /**
     * <code>string gameId = 3;</code>
     */
    public Builder setGameIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ds_ = "";
    /**
     * <code>string ds = 4;</code>
     */
    public java.lang.String getDs() {
      java.lang.Object ref = ds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ds_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ds = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDsBytes() {
      java.lang.Object ref = ds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ds = 4;</code>
     */
    public Builder setDs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ds_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ds = 4;</code>
     */
    public Builder clearDs() {
      
      ds_ = getDefaultInstance().getDs();
      onChanged();
      return this;
    }
    /**
     * <code>string ds = 4;</code>
     */
    public Builder setDsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ds_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:statistics.StorageStatisticKeyProto)
  }

  // @@protoc_insertion_point(class_scope:statistics.StorageStatisticKeyProto)
  private static final org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto();
  }

  public static org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StorageStatisticKeyProto>
      PARSER = new com.google.protobuf.AbstractParser<StorageStatisticKeyProto>() {
    public StorageStatisticKeyProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StorageStatisticKeyProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StorageStatisticKeyProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StorageStatisticKeyProto> getParserForType() {
    return PARSER;
  }

  public org.corps.bi.datacenter.server.statistics.proto.StorageStatisticKeyProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

