// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistic.proto

package org.corps.bi.datacenter.server.statistics.proto;

public interface StorageStatisticKeyProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statistics.StorageStatisticKeyProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string metric = 1;</code>
   */
  java.lang.String getMetric();
  /**
   * <code>string metric = 1;</code>
   */
  com.google.protobuf.ByteString
      getMetricBytes();

  /**
   * <code>string snId = 2;</code>
   */
  java.lang.String getSnId();
  /**
   * <code>string snId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSnIdBytes();

  /**
   * <code>string gameId = 3;</code>
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 3;</code>
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>string ds = 4;</code>
   */
  java.lang.String getDs();
  /**
   * <code>string ds = 4;</code>
   */
  com.google.protobuf.ByteString
      getDsBytes();
}
